#!/bin/sh

CONF="$SNAP_DATA/lighttpd.conf"
BIN="$SNAP/usr/sbin/lighttpd"
SOCKET="/run/php/php8.3-fpm.sock"

PORT=$(snap get laravel-dev lighttpd.port)

if [ -z "$PORT" ]; then
  PORT=80
fi

LC_ALL=C.UTF-8
LANG=C.UTF-8

cat << EOF >"$CONF"
server.modules = (
    "mod_access",
    "mod_alias",
    "mod_compress",
    "mod_fastcgi",
    "mod_indexfile",
    "mod_staticfile",
    "mod_rewrite"
)

server.document-root = "$SNAP_DATA/www"
server.errorlog = "$SNAP_DATA/lighttpd-error.log"
server.pid-file = "$SNAP_DATA/lighttpd.pid"
server.port = $PORT

index-file.names = ( "index.php", "index.html" )

fastcgi.server = ( ".php" =>
    (
        (
            "socket" => "$SOCKET",
            "bin-path" => "",
            "check-local" => "disable",
        )
    )
)

url.rewrite-if-not-file = (
    "^/(?!index\.php|css|images|js|robots\.txt|favicon\.ico)(.*)$" => "/index.php/$1"
)

EOF

mkdir -p "$SNAP_DATA/www"
chmod 0600 "$CONF"

exec "$BIN" -D -f "$CONF"
