#!/bin/sh

CONF="$SNAP_DATA/php-fpm.conf"
BIN="$SNAP/usr/sbin/php-fpm8.3"
SOCKET="/run/php/php8.3-fpm.sock"

LC_ALL=C.UTF-8
LANG=C.UTF-8

mkdir -p /run/php

cat << EOF >"$CONF"
[global]
pid = "$SNAP_DATA/php8.3-fpm.pid"
error_log = /dev/stderr

[www]
listen = "$SOCKET"
user = www-data
group = www-data
pm = dynamic
pm.max_children = 5
pm.start_servers = 2
pm.min_spare_servers = 1
pm.max_spare_servers = 3

EOF

chmod 0600 "$CONF"
chown www-data:www-data /run/php

exec "$BIN" -R --nodaemonize --fpm-config "$CONF"
