name: laravel-dev
base: core24
version: '1.0.3'
summary: A development environment for Laravel applications
description: |
  This snap provides a lightweight web server (lighttpd) with PHP-FPM for developing and testing Laravel applications.

grade: stable
confinement: strict

apps:
  lighttpd:
    command: bin/run-lighttpd
    daemon: simple
    plugs: [network, network-bind, home]
    interfaces: [ :network, :network-bind, :home, :configure ]
  php-fpm:
    command: bin/run-php-fpm
    daemon: simple
    plugs: [network, network-bind]
    interfaces: [ :network, :network-bind ]

architectures:
  - build-on: amd64
  - build-on: arm64

parts:
  lighttpd:
    plugin: nil
    stage-packages:
      - lighttpd
      - php8.3-fpm
      - php8.3-cli
      - php8.3-common
      - php8.3-mysql
      - php8.3-gd
      - php8.3-curl
      - php8.3-mbstring
      - php8.3-xml
      - php8.3-tokenizer
      - php8.3-bcmath
      - php8.3-zip
      - composer
    override-prime: |
      craftctl default
      mkdir -p $CRAFT_PRIME/run/php

  copy-scripts:
    plugin: dump
    source: scripts/
    organize:
      run-lighttpd: bin/
      run-php-fpm: bin/
    after: [lighttpd]

options:
  lighttpd.port:
    type: int
    default: 80
    description: The port lighttpd will listen on.
