name: iotdevice-http # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: A simple IOT Demo web server for wrapper
description: |
  Reboot of the lighttpd snap

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

apps:
  iotdevice-http:
    command: run-lighttpd
    daemon: simple
    plugs: [network, network-bind]
  php-fpm:
    command: run-php-fpm
    plugs: [network, network-bind]
  check-video:
    command: check-video
    daemon: oneshot
    plugs: [network, network-bind]
  check-web:
    command: check-web
    daemon: oneshot
    plugs: [network, network-bind]
    

parts:
  iotdevice-http:
    plugin: nil
    stage-packages:
            - lighttpd
            - spawn-fcgi
            - php
            - php-cgi
            - php-fpm
    override-prime: |
      craftctl default
      #      rm $CRAFT_PRIME/usr/bin/php-cgi
      cp -vf $CRAFT_PRIME/usr/bin/php-cgi.default $CRAFT_PRIME/usr/bin/php-cgi
  check-web:
    plugin: dump
    stage-packages:
           - git
    source: https://github.com/jicheu/demowrapper.git
    override-build: |
      TARGET=$SNAPCRAFT_PART_INSTALL/www
      mkdir -p $TARGET
      cp -vr * $TARGET
  check-video:
    plugin: nil
    stage-packages:
        - wget
    after: [check-web]
  copy:
    plugin: nil
    source: .
    override-build: |
      cp -av run-lighttpd $CRAFT_PART_INSTALL
      cp -av run-php-fpm $CRAFT_PART_INSTALL
      cp -av check-web $CRAFT_PART_INSTALL
      cp -av check-video $CRAFT_PART_INSTALL
    after: [iotdevice-http]
