name: iotdevice-http # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: A simple IOT Demo web server for wrapper
description: |
  Reboot of the lighttpd snap

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

apps:
  iotdevice-lighttpd:
    command: run-lighttpd
    daemon: simple
    plugs: [network, network-bind]
  php-fpm:
    command: run-php-fpm
    daemon: simple
    plugs: [network, network-bind]
  check-video:
    command: check-video
    daemon: oneshot
    plugs: [network, network-bind]
  check-web:
    command: check-web
    plugs: [network, network-bind]
    

parts:
  iotdevice-http:
    plugin: nil
    stage-packages:
            - lighttpd
            - spawn-fcgi
            - php
            - php-cgi
            - php-fpm
    override-prime: |
      craftctl default
      #      rm $CRAFT_PRIME/usr/bin/php-cgi
      cp -vf $CRAFT_PRIME/usr/bin/php-cgi.default $CRAFT_PRIME/usr/bin/php-cgi
  check-video:
    plugin: nil
    stage-packages:
        - wget
  check-web:
    plugin: nil
    stage-packages:
        - git
  copy:
    plugin: nil
    source: .
    override-build: |
      cp -av run-lighttpd $CRAFT_PART_INSTALL
      cp -av run-php-fpm $CRAFT_PART_INSTALL
    after: [iotdevice-http]
